fix bottom over scroll to blank
TwidereProject/TwidereX-Android pull request #102
Opened 2021-05-18 11:24 UTC by HuixingWong

Currently StatusScene page  use  Modifier.fillParentMaxHeight() as  bottom spacer will cause excessive scrolling until blank

2021-05-19 06:10 UTC, Tlaster commented
It's better to have a custom measurement for the last item in the StatusScene since we want to display the last item at least fill the height of the screen. And it's on the roadmap but not implemented yet.

2021-05-20 02:22 UTC, HuixingWong commented
> It's better to have a custom measurement for the last item in the StatusScene since we want to display the last item at least fill the height of the screen. And it's on the roadmap but not implemented yet.

Currently the effect should be consistent with your description

2021-05-20 06:01 UTC, Tlaster requested changes

2021-05-20 06:01 UTC, Tlaster commented on app/src/main/kotlin/com/twidere/twiderex/scenes/StatusScene.kt
> +                                                    spacerHeight =
For this issue, you can avoid calculating the spacer height for measurement, checkout the  `androidx.compose.ui.layout.Layout`, you can use a `Spacer(modifier = Modifier.fillParentMaxHeight())` to get the parent height but don't actually place it.

2021-05-20 14:00 UTC, HuixingWong commented on app/src/main/kotlin/com/twidere/twiderex/scenes/StatusScene.kt
> +                                                    spacerHeight =
Thank you for your remind，Is the current version ok?

2021-05-21 04:09 UTC, Tlaster requested changes

2021-05-21 04:09 UTC, Tlaster commented on app/src/main/kotlin/com/twidere/twiderex/scenes/StatusScene.kt
> +                                            maxHeight -= itemHeight % spacerHeight
Try to avoid maxHeight calculation, you can get the maxHeight by comparing the first and last measuredHeight, and only place this first item.

2021-05-21 05:32 UTC, HuixingWong commented on app/src/main/kotlin/com/twidere/twiderex/scenes/StatusScene.kt
> +                                            maxHeight -= itemHeight % spacerHeight
Changed again,  is it ok?

2021-05-21 05:40 UTC, Tlaster approved these changes
LGTM!

2021-05-21 06:24 UTC, merged