Feature/list timeline
TwidereProject/TwidereX-Android pull request #92
Opened 2021-05-12 09:33 UTC by JoeSteven

Api =>  ListService
	Twitter lists Api
	Mastodon Api  
	Unit test

Repositories:
	ListsRepository
	ListsUserRepository
	Unit test

Paging:
	mediator->list
	source -> ListsSubscribersPagingSource
	unit test	

ViewModel:
	lists
	unit test

Scenes:
	list

2021-05-12 09:53 UTC, JoeSteven commented on app/src/main/kotlin/com/twidere/twiderex/component/lists/MastodonListsModifyComponent.kt
> +object MastodonListsModifyComponentDefaults {
make it private

2021-05-13 05:30 UTC, Tlaster requested changes

2021-05-13 05:31 UTC, Tlaster commented
And add list timeline member in mstdn.jp is not working. return `{"error":"Record not found"}`

2021-05-13 05:39 UTC, JoeSteven commented on app/src/androidTest/java/com/twidere/twiderex/db/DbListTest.kt
> +    private val twitterAccountKey = MicroBlogKey("123", "twitter.com")
done

2021-05-13 05:52 UTC, JoeSteven commented on app/src/main/kotlin/com/twidere/twiderex/component/lists/MastodonListsModifyComponent.kt
> +    var name by remember { mutableStateOf(initName) }
done

2021-05-13 06:01 UTC, JoeSteven commented on app/src/main/kotlin/com/twidere/twiderex/db/model/DbList.kt
> +    fun update(
done

2021-05-13 08:33 UTC, JoeSteven commented on app/src/main/kotlin/com/twidere/twiderex/scenes/lists/platform/TwitterListsEditScene.kt
> +            var isPrivate by remember { mutableStateOf(uiList.isPrivate) }
resolved

2021-05-13 09:16 UTC, JoeSteven commented on app/src/main/kotlin/com/twidere/twiderex/db/CacheDatabase.kt
>      version = 11,
resolved

2021-05-13 09:16 UTC, JoeSteven commented on app/schemas/com.twidere.twiderex.db.CacheDatabase/10.json
> +    "identityHash": "9101e338724db0f85c2ae91610743c33",
resolved

2021-05-13 09:18 UTC, JoeSteven commented
> And add list timeline member in mstdn.jp is not working. return `{"error":"Record not found"}`

resolved by notify user need to follow member first

2021-05-13 09:49 UTC, Tlaster approved these changes
LTGM!

2021-05-13 10:26 UTC, merged